{{- range $modelName, $modelID := $.Values.models }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $modelName }}
  namespace: {{ $.Values.modelNamespace }}
spec:
  storageClassName: {{ include "storageclass-name" $ }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
{{- end }}
