kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.efs.storageClassName | quote }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efs.fileSystemId | quote }}
  directoryPerms: {{ .Values.efs.directoryPerms | quote }}