apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "if-servicenow-agent.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "if-servicenow-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "if-servicenow-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $.Values.appArmor.enabled }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
        {{- end }}
      labels:
        {{- include "if-servicenow-agent.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
            - "python3 cron.py -g {{ .Values.cron.group_size }} -o {{ .Values.cron.offset }} -p {{ .Values.cron.processes }}"
          envFrom:
            - secretRef:
                name: {{ include "if-servicenow-agent.secretName" . }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/conf.d/
            - name: cache
              mountPath: /app/cache
            - name: tmp-volume
              mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "if-servicenow-agent.fullname" . }}-config-cm
      - name: cache
        emptyDir:
          sizeLimit: 128Mi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 128Mi
