{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "if-servicenow-agent.fullname" . }}-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "if-servicenow-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.credentials.authType "basic" }}
  SERVICENOW_USERNAME: {{ .Values.credentials.basic.username | quote }}
  SERVICENOW_PASSWORD: {{ .Values.credentials.basic.password | quote }}
  {{- else }}
  SERVICENOW_OAUTH_CLIENT_ID: {{ .Values.credentials.oauth2.clientId | quote }}
  SERVICENOW_OAUTH_CLIENT_SECRET: {{ .Values.credentials.oauth2.clientSecret | quote }}
  SERVICENOW_OAUTH_USERNAME: {{ .Values.credentials.oauth2.username | quote }}
  SERVICENOW_OAUTH_PASSWORD: {{ .Values.credentials.oauth2.password | quote }}
  {{- end }}
{{- end }}
