{{- if .Values.ariJenkinsAgent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insightfinder.ariJenkinsAgentApiServiceName" . }}
  labels:
    {{- include "insightfinder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ariJenkinsAgent.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "insightfinder.selectorLabels" . | nindent 6 }}
      app: if-ari-jenkins-agent-api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "insightfinder.selectorLabels" . | nindent 8 }}
        app: if-ari-jenkins-agent-api
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ printf "%s-ari-jenkins-agent-api" .Chart.Name }}
          image: "{{ .Values.ariJenkinsAgent.api.image.repository }}:{{ .Values.ariJenkinsAgent.api.image.tag }}"
          imagePullPolicy: {{ .Values.ariJenkinsAgent.api.image.pullPolicy }}
          command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: AGENT_KIND
              value: "jenkins"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "insightfinder.ariJenkinsAgentSecretName" . }}
          readinessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.ariJenkinsAgent.api.resources | nindent 12 }}
      {{- with .Values.ariJenkinsAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ariJenkinsAgent.affinity }}
      affinity:
        {{- toYaml .Values.ariJenkinsAgent.affinity | nindent 8 }}
      {{- else if .Values.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "insightfinder.selectorLabels" . | nindent 18 }}
                  app: if-ari-jenkins-agent-api
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
      {{- end }}
      {{- with .Values.ariJenkinsAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
