apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-demo
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.OOMDemo.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: oom-demo
  template:
    metadata:
      labels:
        app: oom-demo
    spec:
      containers:
      - name: oom-app
        image: polinux/stress-ng
        resources:
          requests:
            memory: "{{.Values.OOMDemo.request}}"
          limits:
            memory: "{{.Values.OOMDemo.limit}}"
        args: ["--vm", "1", "--vm-bytes", "{{.Values.OOMDemo.stress}}", "--timeout", "{{.Values.OOMDemo.wait}}"]