apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: if-kubeactions-crb
subjects:
  - kind: ServiceAccount
    name: if-kubeactions-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: if-kubeactions-role
