apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.fullname" . }}-postgres
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "temporal.fullname" . }}-postgres
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: 5432
    name: postgres
