apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "temporal.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.temporal.replicas }}
  selector:
    matchLabels:
      app: {{ include "temporal.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "temporal.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: temporal
        image: "{{ .Values.temporal.image.repository }}:{{ .Values.temporal.image.tag }}"
        imagePullPolicy: {{ .Values.temporal.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: 7233
        env:
        - name: DB
          value: postgresql
        - name: DB_PORT
          value: {{ .Values.postgres.port | quote }}
        - name: POSTGRES_SEEDS
          value: {{ include "temporal.fullname" . }}-postgres
        envFrom:
        - secretRef:
            name: {{ include "temporal.fullname" . }}-postgres
        resources:
          {{- toYaml .Values.temporal.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 7233
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 7233
          initialDelaySeconds: 30
          periodSeconds: 20
