apiVersion: v1
kind: Service
metadata:
  name: {{ include "nbc-agent.fullname" . }}-receiver
  labels:
    {{- include "nbc-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: receiver
spec:
  type: ClusterIP
  selector:
    {{- include "nbc-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: receiver
  ports:
    - name: http
      port: {{ .Values.receiver.service.port | default 8080 }}
      targetPort: http
      protocol: TCP