apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nbc-agent.fullname" . }}-receiver-config
  labels:
    {{- include "nbc-agent.labels" . | nindent 4 }}
data:
  receiver-config.yml: |
{{ tpl (.Files.Get "files/receiver-config.yaml") . | indent 4 }}