apiVersion: v1
kind: ConfigMap
metadata:
  name: if-saml-cm
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |-
    server:
      port: 8080
    insight-finder:
      serverUrl: {{ .Values.insightfinder.serverUrl }}
      samlUrl: {{ .Values.insightfinder.samlUrl }}
      {{- if .Values.insightfinder.spSecretName }}
      sp-key: /app/certs/sp/sp.key
      sp-cert: /app/certs/sp/sp.crt
      {{- else }}
      sp-key:
      sp-cert:
      {{- end }}

    saml:
      idp:
        {{- range $idpName, $idpConfig := .Values.saml.idp }}
        {{ $idpName }}:
          entity-id: {{ $idpConfig.entityid }}
          firstname-key: {{ $idpConfig.firstnamekey }}
          lastname-key: {{ $idpConfig.lastnamekey }}
          email-key: {{ $idpConfig.emailkey }}
          {{- if $idpConfig.singlesignonurl }}
          singlesignon-url: {{ $idpConfig.singlesignonurl }}
          {{- end }}
          {{- if $idpConfig.idp_cert_provided }}
          idp-cert: /app/certs/idp/{{ $idpName }}.pem
          {{- end }}
        {{- end }}