{{- range $idpName, $idpConfig := .Values.saml.idp }}
{{- if $idpConfig.idp_cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: if-saml-secret-{{ $idpName }}
data:
  {{ $idpName }}.pem: {{ $idpConfig.idp_cert }}
{{- end }}
{{- end }}
