# The main configuration for prometheus to get metric data.
prometheus:
  # The API endpoint for the prometheus server.
  endpoint: "http://prometheus-server.monitor.svc.cluster.local"

  # Prometheus Basic Auth Creadentials. (Optional)
  username: ""
  password: ""

# The main configuration for Loki to get log data.
loki:
  # The API endpoint for loki-gateway server.
  endpoint: "http://loki-gateway.monitor.svc.cluster.local"

  # Loki Basic Auth Creadentials. (Optional)
  username: ""
  password: ""

# The configuration for InsightFinder
insightfinder:
  url: "https://app.insightfinder.com" # The url of InsightFinder.
  user_name: "demoUser" # Username for InsightFinder.
  license_key: "a169dd4e7d7a148e9ec5efa678a9106d44fca534" # license_key for that InsightFinder user.
  system_name: "Kubernetes Demo System" # The system created in InsightFinder website.

# Each project entry is a project that will be created in InsightFinder.
# Projects will get created automatically if they don't exist.
projects:

  - name: k8s-demo-node-metrics
    type: metric
    target: node

  - name: k8s-demo-pod-metrics
    type: metric
    target: pod
    namespace: otel-demo
    hide_component_name_prefix: opentelemetry-demo-

  - name: k8s-demo-pod-logs
    type: log
    target: pod
    namespace: otel-demo
    hide_component_name_prefix: opentelemetry-demo-

  - name: k8s-demo-events
    type: event
    target: namespace
    namespace: otel-demo
    hide_component_name_prefix: opentelemetry-demo-

  - name: k8s-demo-pvc-metrics
    type: metric
    target: pvc
    namespace: otel-demo
    hide_component_name_prefix: opentelemetry-demo-
