apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafkametriccollectoragent.fullname" . }}-config-cm
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |-
    {{- with .Values.config }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
