apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traceserver.fullname" . }}-config
  labels:
    {{- include "traceserver.labels" . | nindent 4 }}
data:
  application.yml: |
    grpc:
      port: {{ .Values.grpc.port }}
      maxInboundMessageSizeInKB: {{ .Values.grpc.maxInboundMessageSizeInKB }}

    {{- with .Values.insightFinder }}
    insightFinder:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.jaeger }}
    jaeger:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.app }}
    app:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.data }}
    data:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.sensitiveData }}
    sensitiveData:
      {{- toYaml . | nindent 6 }}
    {{- end }}