apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "traceserver.fullname" . }}-config
  labels:
    {{- include "traceserver.labels" . | nindent 4 }}
data:
  application.yml: |
    grpc:
      port: {{ .Values.traceserverConfig.grpc.port }}
      maxInboundMessageSizeInKB: {{ .Values.traceserverConfig.grpc.maxInboundMessageSizeInKB }}

    {{- with .Values.traceserverConfig.insightFinder }}
    insightFinder:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.traceserverConfig.jaeger }}
    jaeger:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.traceserverConfig.app }}
    app:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.traceserverConfig.data }}
    data:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.traceserverConfig.sensitiveData }}
    sensitiveData:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  otelcol.yaml: |
    {{- toYaml .Values.otelcolConfig | nindent 4 }}