{{- if .Values.grpcRoute.enabled -}}
{{- include "traceserver.route" (dict
      "root" .
      "kind" "GRPCRoute"
      "name" (include "traceserver.fullname" .)
      "route" .Values.grpcRoute
      "service" (include "traceserver.fullname" .)
      "port" .Values.traceserverConfig.grpc.port) -}}
{{- end }}
