{{- if .Values.grpcRoute.enabled -}}
{{- $svcName := include "traceserver.fullname" . -}}
{{- $svcPort := .Values.traceserverConfig.grpc.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "traceserver.labels" . | nindent 4 }}
  {{- with .Values.grpcRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.grpcRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.grpcRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.grpcRoute.rules }}
    - {{- with .matches }}
      matches:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ $svcName }}
          port: {{ $svcPort }}
          weight: 1
    {{- end }}
{{- end }}
