{{- if and .Values.httpRoute.enabled .Values.traceserverConfig.http -}}
{{- include "traceserver.route" (dict
      "root" .
      "kind" "HTTPRoute"
      "name" (include "traceserver.fullname" .)
      "route" .Values.httpRoute
      "service" (include "traceserver.fullname" .)
      "port" .Values.traceserverConfig.http.port) -}}
{{- end }}
