apiVersion: v1
kind: Service
metadata:
  name: {{ include "traceserver.fullname" . }}
  labels:
    {{- include "traceserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.traceserverConfig.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      appProtocol: grpc
  selector:
    {{- include "traceserver.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "traceserver.fullname" . }}-otelcol
  labels:
    {{- include "traceserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ last (splitList ":" .Values.otelcolConfig.receivers.otlp.protocols.http.endpoint) | int }}
      targetPort: otelcol-http
      protocol: TCP
      name: http
  selector:
    {{- include "traceserver.selectorLabels" . | nindent 4 }}
