apiVersion: v1
kind: Service
metadata:
  name: {{ include "traceserver.fullname" . }}
  labels:
    {{- include "traceserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: {{ .Values.service.portName }}
      appProtocol: grpc
  selector:
    {{- include "traceserver.selectorLabels" . | nindent 4 }}
