apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "if-elasticsearch-collector.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "if-elasticsearch-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "if-elasticsearch-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $.Values.appArmor.enabled }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
        {{- end }}
      labels:
        {{- include "if-elasticsearch-collector.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ $.Values.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: es-config
              mountPath: /app/conf.d/
            - name: tmp-volume
              mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: es-config
        configMap:
          name: {{ include "if-elasticsearch-collector.fullname" . }}-config-cm
      - name: tmp-volume
        emptyDir:
          sizeLimit: 128Mi