{{- if $.Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ printf "%s-limitrange" (include "if-elasticsearch-collector.fullname" .) }}
  namespace: {{ $.Release.Namespace }}
spec:
  limits:
  {{- toYaml $.Values.limitRange.limits | nindent 2 }}
{{- end -}}