apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: if-k8s-agent
  labels:
    app: if-k8s-agent
spec:
  selector:
    matchLabels:
      app: if-k8s-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: if-k8s-agent
    spec:
      serviceAccountName: if-k8s-agent-sa-{{ .Release.Name }}
      securityContext:
        fsGroup: 1001
      containers:
        - name: agent
          tty: true
          imagePullPolicy: Always
          image: "docker.io/insightfinderinc/kubernetes-agent:{{.Chart.AppVersion}}"
          volumeMounts:
            - name: config
              mountPath: /app/conf.d
            - name: storage-{{ .Release.Name }}
              mountPath: /app/storage
      volumes:
        - name: config
          configMap:
            name: if-k8s-agent-cm
            items:
              {{- range $key, $project := .Values.projects }}
                - key: {{ $project.name }}.ini
                  path: {{ $project.name }}.ini
              {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: storage-{{ .Release.Name }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  serviceName: svcname-{{ .Release.Name }}