{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bedrock-access-gateway-manager.fullname" . }}
  labels:
    {{- include "bedrock-access-gateway-manager.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bedrock-access-gateway-manager.fullname" . }}
  labels:
    {{- include "bedrock-access-gateway-manager.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bedrock-access-gateway-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "bedrock-access-gateway-manager.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
