apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "if-prometheus-agent.fullname" . }}
  namespace: {{ $.Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "if-prometheus-agent.fullname" . }}-leader-election
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "if-prometheus-agent.fullname" . }}-leader-election
  namespace: {{ $.Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "if-prometheus-agent.fullname" . }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "if-prometheus-agent.fullname" . }}-leader-election
  apiGroup: rbac.authorization.k8s.io
