replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: docker.io/insightfinderinc/llm-trace-proxy
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 2
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}

config:
  proxy:
    target: "modelserving.svc.cluster.local" # Target subdomain URL for routing requests
  aw:
    endpoint: "http://insightfinder-aw.insightfinder.svc.cluster.local"
  trace:
    endpoint: 'http://localhost:4316'
    serviceName: "test-llm-trace-proxy"