apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "if-otlpserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "if-otlpserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "if-otlpserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "if-otlpserver.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ printf "%s-otlpserver" .Chart.Name }}
        {{- with $.Values.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- else }}
        resources:
          limits:
            cpu: "2"
            memory: "1024Mi"
          requests:
            cpu: "1"
            memory: "512Mi"
        {{- end }}
        ports:
        - name: otlp-svc
          containerPort: 4317
          protocol: TCP
        volumeMounts:
        - name: config-data
          mountPath: "/app/data.yaml"
          subPath: data.yaml
          readOnly: true
        - name: config-server
          mountPath: "/app/server.yaml"
          subPath: server.yaml
          readOnly: true
      volumes:
      - name: config-data
        configMap:
          name: {{ include "if-otlpserver.configMapName" . }}
          items:
          - key: data.yaml
            path: data.yaml
      - name: config-server
        configMap:
          name: {{ include "if-otlpserver.configMapName" . }}
          items:
          - key: server.yaml
            path: server.yaml