apiVersion: v1
kind: Service
metadata:
  name: {{ include "if-otlpserver.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "if-otlpserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "if-otlpserver.selectorLabels" . | nindent 4 }}
  ports:
  - name: otlp-svc
    protocol: TCP
    port: 4317
    targetPort: otlp-svc