apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-audit-log-config
data:
  config.ini: |
    [loki]
    endpoint = {{ .Values.loki.endpoint }}
    username = {{.Values.loki.username}}
    password = {{.Values.loki.password}}
    
    # Query to get audit log
    query = {{.Values.collector.query}}
    
    # Epoch time WITHOUT millisec   sample: 1699285077
    startTime = {{.Values.collector.startTime}}
    endTime = {{.Values.collector.endTime}}

    [insightfinder]
    user_name = {{.Values.insightfinder.user_name}}
    license_key = {{.Values.insightfinder.license_key}}
    project_name = {{.Values.insightfinder.project_name}}
    system_name = {{.Values.insightfinder.system_name}}
    project_type = log
    if_url = {{.Values.insightfinder.url}}