{{- if and .Values.temporal.enabled (eq .Values.temporal.mode "dev") .Values.temporal.dev.persistence.enabled (not .Values.temporal.dev.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-temporal-data" (include "insightfinder.fullname" .) }}
  labels:
    {{- include "insightfinder.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.temporal.dev.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.temporal.dev.persistence.size }}
{{- end }}
