{{- if .Values.temporal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insightfinder.temporalServiceName" . }}
  labels:
    {{- include "insightfinder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.temporal.service.type }}
  selector:
    {{- include "insightfinder.selectorLabels" . | nindent 4 }}
    app: if-temporal
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.temporal.service.port }}
      targetPort: grpc
    {{- if eq .Values.temporal.mode "dev" }}
    - name: ui
      protocol: TCP
      port: {{ .Values.temporal.dev.uiPort }}
      targetPort: ui
    {{- end }}
{{- end }}
