{{- if and .Values.temporal.enabled (eq .Values.temporal.mode "postgres") .Values.temporal.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insightfinder.temporalWebServiceName" . }}
  labels:
    {{- include "insightfinder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.temporal.web.service.type }}
  selector:
    {{- include "insightfinder.selectorLabels" . | nindent 4 }}
    app: if-temporal-web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.temporal.web.service.port }}
      targetPort: http
{{- end }}
