collector:
  query: '{namespace="insightfinder",pod=~".*appserver.*"} |= `com.insightfinder.models.AuditLog`'

  # Epoch time WITHOUT millisec   sample: 1699285077
  # Leave empty for live streaming.
  startTime:
  endTime:


loki:
  endpoint: http://loki-gateway.monitor
  username: 
  password: 

insightfinder:
  url: https://stg.insightfinder.com
  user_name: user
  license_key: 
  system_name: 
  project_name: 