apiVersion: v1
kind: ConfigMap
metadata:
  name: kservectl-accelerators
data:
{{ (.Files.Glob "files/accelerators.yaml").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kservectl-models
data:
  llm_models.yaml: |
    models:
{{ .Values.models | toYaml | indent 6 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kservectl-sites-url
data:
  sites_url.yaml: |
    sites_url:
{{ .Values.sites_url | toYaml | indent 6 }}