apiVersion: v1
kind: ConfigMap
metadata:
  name: config-models
data:
{{ tpl (.Files.Glob "files/llm_models.yaml").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-accelerators
data:
{{ (.Files.Glob "files/accelerators.yaml").AsConfig | indent 2 }}
