apiVersion: v1
kind: ConfigMap
metadata:
  name: kservectl-accelerators
data:
  accelerators.yaml: |
    {{- with .Values.node_selector_key }}
    node_selector_key: {{ . }}
    {{- end }}
    {{- with .Values.default_accelerator }}
    default_accelerator: {{ . }}
    {{- end }}
    accelerators:
{{ .Values.accelerators | toYaml | indent 6 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kservectl-presets
data:
  presets.yaml: |
    presets:
{{ .Values.presets | toYaml | indent 6 }}
