apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kservectl.fullname" . }}
rules:
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kservectl.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kservectl.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "kservectl.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
