apiVersion: v2
name: nbc-agent
description: A Helm chart for InsightFinder / NBC data streaming agent
type: application
<<<<<<< Updated upstream
<<<<<<< Updated upstream
version: 0.1.9
=======
version: 0.1.10
>>>>>>> Stashed changes
=======
version: 0.1.10
>>>>>>> Stashed changes
