apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "if-loki-agent.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "if-loki-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "if-loki-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $.Values.appArmor.enabled }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
        {{- end }}
      labels:
        {{- include "if-loki-agent.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "LOKI_AGENT_CONFIG_PATH"
            value: "/app/configs/config.yaml"
          - name: "LOKI_AGENT_LOG_LEVEL"
            value: "{{ .Values.config.agent.log_level }}"
          - name: "LOKI_AGENT_RUN_INTERVAL"
            value: "{{ .Values.config.insightfinder.run_interval_in_seconds }}"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/configs/config.yaml
              subPath: config.yaml
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "if-loki-agent.fullname" . }}-config-cm