apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "if-insightfinder-rawlogs.fullname" . }}-config-cm
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "if-insightfinder-rawlogs.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
