apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "if-insightfinder-rawlogs.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "if-insightfinder-rawlogs.labels" . | nindent 4 }}
