apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-collector-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-collector-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-collector-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $.Values.appArmor.enabled }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
        {{- end }}
      labels:
        {{- include "kafka-collector-agent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config.properties
              subPath: config.properties
              readOnly: true
            - name: logs
              mountPath: /app/logs
            - name: tmp
              mountPath: /tmp
            {{- if or .Values.ssl.keystoreBase64 .Values.ssl.truststoreBase64 }}
            - name: ssl
              mountPath: /app/ssl
              readOnly: true
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kafka-collector-agent.fullname" . }}-config
        - name: logs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{- if or .Values.ssl.keystoreBase64 .Values.ssl.truststoreBase64 }}
        - name: ssl
          secret:
            secretName: {{ include "kafka-collector-agent.fullname" . }}-ssl
        {{- end }}
