# Default values for if-prometheus-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: insightfinderinc/redis-agent
  pullPolicy: Always
  # Tag example: "latest@sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229"
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

appArmor:
  enabled: false

limitRange:
  enabled: false
  limits:
    - default:
        cpu: "8"
        memory: "8Gi"
      defaultRequest:
        cpu: "500m"
        memory: "500Mi"
      type: Container

resourceQuota:
  enabled: false
  spec:
    hard:
      cpu: "24"
      memory: 24Gi
      pods: "3"

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 200m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

configs:
  - redis:
      # Only explicitly provided nodes will be queried in single mode
      redis_hosts: localhost:7001
      # redis mode - either 'cluster' or 'single'
      redis_mode: cluster
      # authentication
      password: 
      # SSL/TLS configuration
      use_ssl: False
      ssl_ca_certs: 
      ssl_certfile: 
      ssl_keyfile: 
      # connection timeout in seconds
      connection_timeout: 5
      # connection pool
      max_connections: 10

      ## key monitoring configuration
      # regex pattern to filter keys (leave empty to check all keys)
      key_pattern: '*'
      # Whether to scan keys or use KEYS command (scan is more efficient for large databases)
      use_scan: True
      # scan count parameter
      scan_count: 1000
      # If set to True, will also check TTL for keys (disabled by default as we only want idle time)
      check_ttl: False
      # number of thread to used in the pool, default is 4
      thread_pool:
      # number of the worker processes, default is count_of_cpu * 4
      processes:
      # minutes the main process wait for workers to finish, default is 5
      timeout:

      ## proxy
      agent_http_proxy:
      agent_https_proxy:

    insightfinder:
      user_name:
      license_key:
      # Name of the project created in the InsightFinder UI, If this project is not exist, agent will create it automatically.
      project_name:
      # Name of system owned by project. If project_name is not exist in InsightFinder, agent will create a new system automatically from this field or project_name.
      system_name:
      # Set to `YES` if project is container.
      containerize:
      # Set to empty to create normal projects
      # set to 'vm' to use 'DynamicVM' as the AgentType, set to 'host' to use 'DynamicHost' as the AgentType
      dynamic_metric_type:
      sampling_interval:
      run_interval:
      # what size to limit chunks sent to IF to, as kb
      chunk_size_kb:
      if_url:
      if_http_proxy:
      if_https_proxy: