{{- if not .Values.licenseKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ubs-agent.fullname" . }}-license
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ubs-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "ubs-agent.licenseSecretKey" . }}: {{ .Values.licenseKey.value | quote }}
{{- end }}
