apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "if-globalview-streaming.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "if-globalview-streaming.labels" . | nindent 4 }}
