# Default values for if-loki-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: insightfinderinc/loki-agent
  pullPolicy: Always
  # Tag example: "latest@sha256:cb5c1bddd1b5665e1867a7fa1b5fa843a47ee433bbb75d4293888b71def53229"
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

podAnnotations: {}

appArmor:
  enabled: false

limitRange:
  enabled: false
  limits:
    - default:
        cpu: "4"
        memory: "4Gi"
      defaultRequest:
        cpu: "200m"
        memory: "200Mi"
      type: Container

resourceQuota:
  enabled: false
  spec:
    hard:
      cpu: "12"
      memory: 12Gi
      pods: "3"

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 200m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Loki Agent Configuration
config:
  agent:
    data_format: "json"
    timezone: "UTC"
    log_level: "INFO"
    filters_include: ""
    filters_exclude: ""

  loki:
    base_url: "http://localhost:8080"
    username: "admin"
    password: "admin"
    verify_ssl: false
    max_concurrent_requests: 10
    max_retries: 3
    query_timeout: 60
    max_entries_per_query: 1000
    default_instance_name_field: "app"
    
    queries:
      - name: "insightfinder_audit_logs"
        query: '{namespace="insightfinder",pod=~".*appserver.*"} |= `com.insightfinder.models.AuditLog`'
        enabled: true
        labels:
          source: "insightfinder"
          type: "audit"
        component_name_field: "container"
        container_name_field: "node_name"
      
      - name: "application_errors"
        query: '{namespace="insightfinder"} |~ "ERROR|Exception|FATAL"'
        enabled: true
        labels:
          source: "insightfinder"
          type: "error"
        component_name_field: "container"
        container_name_field: "pod"
      
      - name: "kubernetes_events"
        query: '{namespace=~"kube-.*|default"} |= "Event"'
        enabled: true
        labels:
          source: "kubernetes"
          type: "event"
        instance_name_field: "container"
        component_name_field: "instance"
        container_name_field: "pod"

  insightfinder:
    server_url: "https://app.insightfinder.com"
    username: ""
    license_key: ""
    
    logs_project_name: "loki-logs"
    logs_system_name: "loki-system"
    logs_project_type: "LOG"
    
    sampling_interval: 60
    cloud_type: "OnPremise"
    instance_type: "OnPremise"
    is_container: true
    
    http_proxy: ""
    https_proxy: ""
    
    chunk_size: 2097152
    max_packet_size: 10485760
    retry_times: 3
    retry_interval: 5