apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nbc-metadata-agent.fullname" . }}
  labels:
    {{- include "nbc-metadata-agent.labels" . | nindent 4 }}
data:
  application.yaml: |
    {{- .Values.config | nindent 4 }}
